'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Exploring_The_Bleak.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _10floor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_10floor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1floor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1floor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2floor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2floor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3floor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_3floor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _4floor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_4floor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _5floor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_5floor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _6floor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_6floor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _7floor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_7floor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _8floor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_8floor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _9floor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_9floor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Backstab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Backstab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Block() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Block", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BloodSplatter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BloodSplatter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BoneShield() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BoneShield", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BrickWall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BrickWall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Clumsiness() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Clumsiness", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CommentBox1_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CommentBox1_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CommentBox10_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CommentBox10_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CommentBox11_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CommentBox11_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CommentBox2_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CommentBox2_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CommentBox3_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CommentBox3_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CommentBox4_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CommentBox4_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CommentBox5_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CommentBox5_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CommentBox6_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CommentBox6_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CommentBox7_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CommentBox7_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CommentBox8_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CommentBox8_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CommentBox9_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CommentBox9_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Counter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Counter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DoubleSlice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DoubleSlice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Empower() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Empower", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FireArrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FireArrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fireball() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fireball", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FireShield() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FireShield", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fury() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fury", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Heal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Heal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Hide() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hide", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Hit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HolyBolt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HolyBolt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Immolate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Immolate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Inventory() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Inventory", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Kick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Kick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Lava() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lava", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Leech() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Leech", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MagicShield() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MagicShield", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MetalFloor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MetalFloor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Punch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Punch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RockWall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RockWall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Runestrike() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Runestrike", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sacrifice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sacrifice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Shoot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Shoot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Silence() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Silence", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Slice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Slice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Splash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Splash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property StairsDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StairsDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property StairsUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StairsUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Strike() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Strike", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stun() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stun", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Trip() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Trip", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TripleSlice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TripleSlice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Water() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Water", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Whisper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Whisper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Wound() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Wound", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
